name: Notification Discord

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"username\": \"CI Bot\", \"content\": \"📢 Notification GitHub\nRepo: $GITHUB_REPOSITORY\nCommit: $GITHUB_SHA\nPar: $GITHUB_ACTOR\"}" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}